#!/bin/sh

# This is a sample DAEMON file which is started at boottime. iIt must be names
# "start" here and will be renamed according to your Pluginname during
# installation. CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boottime!

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

if [ ! -f /etc/apt/sources.list.d/nodesource.list ]
then 
    /usr/bin/logger "Raumserver installation: nodesources repo not installed. Starting installation now."
    # Nodejs current is recommended as of
    #  https://github.com/ChriD/node-raumserver#requirements
    curl -sL https://deb.nodesource.com/setup_8.x | bash
fi

# Test if nodejs is installed otherwise install it: 
if [ `which nodejs > /dev/null; echo $?` -ne 0 ]
then 
    /usr/bin/logger "Raumserver installation: nodejs not installed. Starting installation now."
    apt-get -y install nodejs
fi

if [ -d '/opt/loxberry/data/plugins/raumserver' ]
then 
    # change to raumserver folder
    cd /opt/loxberry/data/plugins/raumserver
    
    #check if raumserver already installed
    if [ `npm list | grep -c "node-raumserver"` -ne 1 ]
    then
        /usr/bin/logger "Raumserver installation: node module raumserver not instlled. Starting installation now."
        # otherwise install the server
        npm install github:ChriD/node-raumserver
    fi

    /usr/bin/logger "Raumserver: starting."
    #run the server: 
    node node_modules/node-raumserver/raumserver.js

    if [ `ps ax | grep -v grep | grep -c node_modules/node-raumserver/raumserver.js` -eq 1 ]
    then
        /usr/bin/logger "Raumserver: Start successful."
    else
        /usr/bin/logger "Raumserver: Start failed."
    fi
fi

exit 0
